source 'https://rubygems.org'
gem 'nokogiri'
gem 'rails', '3.0.0.beta3'
gem 'rack', '>=1.0'
gem 'thin', '~>1.1'
gem 'rspec', :require => 'spec' #gem 'rspec', :require => false
gem 'sqlite3'
gem 'nokogiri', :git => 'https://github.com/tenderlove/nokogiri.git', :branch => '1.4'
ruby '2.5.3.'
gem 'pry'
gem 'roo'
gem 'bundler'
